version: '3.7'

services:
    spigot:
        build:
            context: .
            dockerfile: Dockerfile
        image: spigot
        container_name: spigot
        ports:
            - 25565:25565
        environment: 
            - XMS=500M
            - XMX=1G
        volumes: 
            - ./configs/eula.txt:/spigot/eula.txt
            - ./configs/server.properties:/spigot/server.properties
            - ./plugins:/spigot/plugins
            - ./world/world:/spigot/world
            - ./world/world_nether:/spigot/world_nether
            - ./world/world_the_end:/spigot/world_the_end
        networks: 
            - minecraft_spigot
    
    mysql:
        image: mysql:8
        container_name: mysql
        environment: 
            - MYSQL_DATABASE=spigot
            - MYSQL_USER=spigotusr
            - MYSQL_PASSWORD=supersecretpassword
            - MYSQL_ROOT_PASSWORD=supersecretrootpassword
        volumes: 
            - db_data:/var/lib/mysql
        networks: 
            - minecraft_spigot

volumes: 
    db_data:
    spigot_world:
    spigot_world_nether:
    spigot_world_the_end:

networks:
    minecraft_spigot:
